script: |
  cd /home/ubuntu

  if [ ! -d "Website_CI-CD" ]; then
    git clone https://github.com/abhinav-sharma-dev/Website_CI-CD.git
  fi

  cd Website_CI-CD
  git pull origin main

  docker stop website || true
  docker rm website || true
  docker build -t website .
  docker run -d -p 80:80 --name website website
